### ISSUE TITLE
Black background on iterm with spacebar

### ISSUE THREAD

**Issue by henryiii** [vinayak-mehta/present#29]
After the first slide (which is fine), I get this:

<img width="495" alt="Screen Shot 2020-08-26 at 11 04 50 PM" src="https://user-images.githubusercontent.com/4616906/91379430-ad119780-e7f0-11ea-9aa5-6b77e29cfebf.png">

On macOS & iTerm.

**Comment by vinayak-mehta** [comment]
Oh no! I have no experience with macOS and iTerm so will have to find a way to debug this. Can you tell me what the output is when you explicitly set the background color for this slide using `<-- fg=black bg=white -->`? What about other slides?

**Comment by henryiii** [comment]
The background/foreground colors only change the lines with actual non-space text, it remains suspended in black soup.

**Comment by tmroyal** [comment]
I have additional light to shed on the issue. 

This indeed happens to me when I press the space key. But when I hit 'f', 'b', left or right, it works as intended. 

This is in iTerm2 3.3.12 and Terminal 2.9.5 on macOS 10.14.6.

<img width="680" alt="presentWorkingOnMacOS" src="https://user-images.githubusercontent.com/1308481/91476447-01595d80-e86b-11ea-98f5-3df812154dba.png">

Colors are off because of my own terminal theme.

**Comment by henryiii** [comment]
Ahh, I did not try anything other than a space bar.

**Comment by vinayak-mehta** [comment]
@henryiii Did using arrow keys solve the issue?

@tmroyal Thanks for raising a PR! I'll merge it right now.

**Comment by vinayak-mehta** [comment]
@henryiii With the next release you should be able to press spacebar to go to the next slide!
