### ISSUE TITLE
(Slide 4) BlockQuote is not supported

### ISSUE THREAD

**Issue by Lazloo** [vinayak-mehta/present#64]
I tried the sample.md. But I got the following error:

![grafik](https://user-images.githubusercontent.com/10186284/91830320-eb6ce380-ec42-11ea-93f6-b37e236b2a1d.png)

**Comment by vinayak-mehta** [comment]
Upgrading to `0.5.1` should solve this.

**Comment by Lazloo** [comment]
Version 0.5.1. seems not yet to be available using pip on windows

**Comment by vinayak-mehta** [comment]
What install commands did you use? If you're using pip, you can try doing `python3 -m pip install --upgrade present`. What's the output that you get with this command?

**Comment by Lazloo** [comment]
interesting:

python3 -m pip install present -> works
pip install present -> installs present 0.4.0

Only python 3 is installed

**Comment by Lazloo** [comment]
Maybe this warning helps:

![grafik](https://user-images.githubusercontent.com/10186284/91845520-98525b00-ec59-11ea-87ef-9f91b691e11a.png)

**Comment by vinayak-mehta** [comment]
Yes, I've yanked releases older than 0.5.0 so everyone should see a warning if pip installs older versions.

**Comment by Lazloo** [comment]
But why is pip installing an old version?

**Comment by vinayak-mehta** [comment]
I forgot to add a `python_requires>=3.7` in the setup.py for the old versions, it only got added in 0.5.0. So during the install pip doesn't take your Python version into account and still installs an older present version since it thinks thats compatible. Maybe I should just delete older releases from PyPI, let me look into the consequences of that.
